sudo: false
language: ruby
cache: bundler
rvm:
- 2.6
- 2.7
notifications:
  slack:
    secure: JcaUwy2K2x3nLZeU5sjMy+LPWd6SUey5FExLJf70QTSaioyYJgyvKgexZ7sR5kUEwkps+Ql9smUBUho/H/FeEEjnTidv/kq1+Fvo0Hr17VMrEuWA4m1XyMGP3TChfW1aPm2z+aL3AhX/voORD9CIevoC3GlZmDTq3aaB6T5EQGxpEqRkutJ4B9c94uEoZWaY+7w5r3c+CxQxr3lt5jiDkNzTySPDcs3s+zf/8AMoz3gwisoL0RkL5dv/80c8k/mzkYtu9V97tMK2V9sA35cU9Xnc0K8CEtJiWwx9JPvqrFQ2QQion3g9cMLzdBvmJYOazlCPaK19AJ2PfIO0JJKeJIWsSxBW3lTEUKRRXJvC+xY/HlLCNzXyRUn2TYr8Px0bQEIG1wGZdJvqBYG9xeuzgXjHRBPfCGVkXvU6xaGCIfRMoWodj7gknJCv7uimOJYLg5c57Q4sWnbp+kxtiHYSqn41j1aPkopsUL7wHCzwSscS4PbWTVyoHsXfy+P9c77pt/uLwf0he99+j4kgHsCaxPAUJ7aeTmpR8/n02rii9Vf4eWyIOKXq73FVT/Hatn/tuB72z1OmpuaGPXoWmJoo52XQRPBRwlX9fBMFklcwyAts9PG7VvB5s6l+dnSht1v44qjTGsT78nqQbUgp0lNcU3G67ld0OIvG3MkGCAZ+AL4=
